export const apiEndPoints = {
    login: "auth/sign_in",
    SignUp: "auth/sign_up",
    getHomeData: "getHomePageData",
    sendMessage: "sendMessage",
    profile: {
        ChangeProfile: "user/updateProfile",
        resetPassword: "user/updatePassword",
        getUserData: "user/getUserData",
        checkEmail: "forgot-password",
        getUserFavourite: "user/getUserFavourite",
        getOrders: "user/getOrders",
    },
    location: {
        getUserAddresses: "user/getUserAddresses",
        addLocation: "user/addLocation",
        updateLocation: "user/updateLocation/",
        deleteLocation: "user/deleteLocation/",
    },
    cart: {
        getCartData: "user/getCartData",
    },
    addOrRemoveFavourite: "user/addOrRemoveFavourite",
    addToCart: "user/addBooksToCart",
    deleteBooksFromCart: "user/deleteBooksFromCart",
    getBookData: "getBookData",
    checkout: "user/checkout",
    getPartners: "getPartners",
    getClasses: "getClasses",
    getSubjects: "getSubjects",
    searchBook: "searchBook",
    getFooterData: "getFooterData",
    getPublicPageData: "getPublicPageData",
    getClass: "getClass",
    getSubject: "getSubject",
};
